### ISSUE TITLE
Upgrade to v2.6.x (blocked upstream)

### ISSUE THREAD

**Issue by eprovst** [macexx/EAP-Controller#1]
I don't know how much work that would be or if there is a personal reason to stick with v2.5.3. However v2.6.0 brings some updates to captive portal which would be useful.

Thanks for the image by the way, it works great!

**Comment by macexx** [comment]
They haven't released 2.6 for Linux yet, (v2.5.3. is still the latest Linux release), I will update it as soon as there is a new release and I got a proper fix for an update procedure. 

They promised big updates on the forums for the next linux release, so will see what that means, today "user storage is around 4gb and alot of it is mongodb", and certificates are hardcoded to use "tplink" as password,... (so alot of room for improvments)

But aye will release it as soon as it hits(if there will be any significant change to upgrades i will update the readme)

//mac

**Comment by eprovst** [comment]
Oh, I hadn't noticed their Linux releases weren't in sync with the Windows version...
Sorry about that.
