### ISSUE TITLE
Plans for Omada version 4

### ISSUE THREAD

**Issue by ruslanguns** [macexx/EAP-Controller#10]

**Comment by dpeart** [comment]
Interested as well, as I want to upgrade the firmware, but it needs version 4 to do so.

**Comment by macexx** [comment]
Better late the never ;) nope there is a great docker for that "mbentley/omada-controller".

Not running Omada any more converted all my "EAP" products to Openwrt (for WPA-Enterprise support and continued security patches).
So running custom script(s), CLI for management and ELK stack for monitoring.
