### ISSUE TITLE
Doesn't work on Mac / Windows with Docker for Mac / Windows

### ISSUE THREAD

**Issue by cored0wn** [macexx/EAP-Controller#2]
I've just tried to get this image running on my mac machine. Unfortunately it doesn't work because docker for mac (and docker for windows) doesn't support bridge mode for the network. (See https://docs.docker.com/docker-for-mac/networking/#there-is-no-docker0-bridge-on-macos)

At the moment I try to find a workaround so I get the image running. As soon as I have new insights, I'll post them here.

**Comment by cored0wn** [comment]
I've found out that I can access the container if I start them with the following command:
`docker run -d --privileged --name="eap" -p 8088:8088 -p 8043:8043 mace/eap-controller`

I have to go inside the running container and start run the following command:
```
docker exec -it eap bash
# Repeat this command until you get the response "Start successfully"
tpeap start 
```

**Comment by bazaglia** [comment]
Actually, it seems `--net: host`, in case of Mac, maps to the VM IP address, not to system `localhost`. But it's not clear to me how to get the VM IP address...

**Comment by macexx** [comment]
@cored0wn 
If you are gonna do bridged networking you better open all the ports that is needed might be while it fails to start.

8043 (TCP) for https, 8088 (TCP) for http, 27001 (UDP) for controller discovery, 27002 (TCP) for controller searching, 29810 (UDP) for EAP discovery, 29811 (TCP) for EAP management, 29812 (TCP) for EAP adoption, 29813 (TCP) for EAP upgrading. Make sure these ports are not occupied by other applications when you run EAP controller.

**Comment by bazaglia** [comment]
@macexx exactly, this was I end up doing too. I got the ports from some TP-LINK docs I found and this was my resulting docker run:

```
docker run -d -v eap-controller:/config -p 29810:29810/udp -p 29811:29811 -p 29812:29812 -p 29813:29813 -p 8088:8088 -p 8043:8043 -it mace/eap-controller
```

**Comment by macexx** [comment]
@bazaglia 

It works as expected running bridged? 

BTW
You could always open a shell to your container and check the ip, (to see whats up with "--net: host" )
1, Run "docker ps -a"
2, Open a shell to the docker "docker exec -it eap(id or name from the command above) /bin/bash"
3. run " ifconfg"

Another good check is to run docker logs "(id or name from the command above)" to see if eap gets stuck on something on boot.

**Comment by bazaglia** [comment]
@macexx Oh yeah it works as expected with the command I pasted above. I could set up two EAP's  2 days ago.
