### ISSUE TITLE
Cannot start with host network

### ISSUE THREAD

**Issue by Azazel666** [macexx/EAP-Controller#4]
I have a server running in a bare metal vmware, i run it as a media server and use all kinds of docker container in it. I have EAP controller running on my desktop computer but i want to move it to a docker container instead on my media server so i tried this docker container.
I can get it to start when not using host network, but then i cannot se the access point, and when i run it with host network i cannot get it to start.

Here is my docker compose settings:
`eap-controller:
    container_name: eap-Controller
    image: mace/eap-controller
    restart: always
    ports:
     - "8088:8088"
     - "8043:8043"
    volumes:
     - ${USERDIR}/eap-controller:/config
     - "/etc/localtime:/etc/localtime:ro"
    environment:
     - PUID=${PUID}
     - PGID=${PGID}
     - TZ=${TZ}
    network_mode: host`

I have checked the logs in the docker container but cannot find anything wrong.
/opt/tplink/EAPController/logs/startup.log
`log4j:WARN No appenders could be found for logger (com.tp_link.eap.util.system.SystemUtil).
log4j:WARN Please initialize the log4j system properly.
========EAP_LINUX_MONGOD_KEY======
mongodPath = "/opt/tplink/EAPController/bin/mongod" --journal --port 27017 --dbpath "/opt/tplink/EAPController/data/db" -pidfilepath "/opt/tplink/EAPController/data/mongo.pid" --logappend--logpath "/opt/tplink/EAPController/logs/mongod.log" --nohttpinterface --bind_ip 127.0.0.1
repairCommand = "/opt/tplink/EAPController/bin/mongod" --repair --dbpath "/opt/tplink/EAPController/data/db" --logappend --logpath "/opt/tplink/EAPController/logs/mongod.log"
"/opt/tplink/EAPController/bin/mongod" --journal --port 27017 --dbpath "/opt/tplink/EAPController/data/db" -pidfilepath "/opt/tplink/EAPController/data/mongo.pid" --logappend --logpath "/opt/tplink/EAPController/logs/mongod.log" --nohttpinterface --bind_ip 127.0.0.1
`

/opt/tplink/EAPController/logs/server.log:
`2018-08-13 09:45:57 [main] [INFO]-[ConfigurationFactory.java:39] - success to load configuration : eap.properties
2018-08-13 09:45:57 [main] [INFO]-[ConfigurationFactory.java:39] - success to load configuration : mongodb.properties
2018-08-13 09:45:57 [main] [INFO]-[ConfigurationFactory.java:39] - success to load configuration : jetty.properties
2018-08-13 09:45:57 [main] [INFO]-[ConfigurationFactory.java:39] - success to load configuration : netty.properties
2018-08-13 09:45:57 [main] [INFO]-[ConfigurationFactory.java:39] - success to load configuration : log4j.properties
2018-08-13 09:45:57 [main] [INFO]-[ConfigurationFactory.java:39] - success to load configuration : device.properties
2018-08-13 09:45:57 [main] [INFO]-[ConfigurationFactory.java:39] - success to load configuration : user.params.properties`

trying to start it manually inside the container with, tpeap start
`Starting EAP Controller ........../usr/bin/tpeap: line 79:   863 Killed                  nohup $JAVA_TOOL -server -Xms128m -Xmx1024m -XX:MaxHeapFreeRatio=60 -XX:MinHeapFreeRatio=30 -XX:+UseSerialGC -XX:+HeapDumpOnOutOfMemoryError -Deap.home="${eapHome}" -cp ${eapHome}"/lib/com.tp-link.eap.start-0.0.1-SNAPSHOT.jar:"${eapHome}"/lib/*" com.tp_link.eap.start.EapMain start > ${eapHome}/logs/startup.log 2>&1
................................................................................................................
Start failed.`

As far as i can see the mongo db is working when looking on the log.
/opt/tplink/EAPController/logs/mongod.log:
https://pastebin.com/v2QJVpHy

Any idea what to look for next to get this running ?

**Comment by Azazel666** [comment]
Managed to get it working, seams my issue was i didn't shutdown my other eap controller running on my desktop. Since i could start another eap controller on my laptop in the same network i thought it shoulden't be a problem and i wanted to get the docker container running before shutting down my desktop controller. But after closing both controllers (desktop and laptop) it started.

**Comment by macexx** [comment]
Aye I ran into this as well when creating the docker so I put a note on it in the Readme.
