### ISSUE TITLE
Assigning a static ip

### ISSUE THREAD

**Issue by stevetogo** [macexx/EAP-Controller#6]
I had this working for the last few months and my server crashed and lost the configs. How do i set this up with a static ip address? I am using it in my QNAP NAS

**Comment by macexx** [comment]
Wow, such an old question an it was flagges as dated 2020, sry for that, guess its no longer an issue.

However this is an docker issue as of "macvlan" no idea what version QNAP i useing but guess as the date i´m writing this they are using an up to date version  ;)

Well some or from what iv´e gathered alot of NAS greaters have there own docker cli.

But from pure command line, to create an mac vlan netwotk.
It would be simmilar to

docker network create -o parent=br1 --driver macvlan  --subnet 192.168.2.0/24  --ip-range 192.168.2.128/26 --gateway 192.168.2.1 localnetwork

Then yo use the docker just use the "netwotk option"when you tun your container to something simmilar to:
docker run--network  localnetwork "ip(192.168.2.209)"

Well beeing this old i guess qnap has something own build for this. so closeing this
