### ISSUE TITLE
Do I still need a hardware AC to control the APs?

### ISSUE THREAD

**Issue by t0ny-peng** [macexx/EAP-Controller#9]
Hi there. First thanks for making it a docker image. Second, I'm currently using a AC100 to control all the APs in my home. Just wonder if it's possible to replace it by the EAP controller, so that I can get rid of the big blue box. Thanks!

**Comment by macexx** [comment]
Hi, sorry for the very late replay.

Wow dident know tp-link made harware controllers (thats really great for enterprise)s.
There really isent alot of information about the controller online, except in chinese markets.

So my suggestion is install the windows based controller on your pc, to test (same as the docker).

Tp-link wont play nice if there is two controllers on your network so wait a fwee minutes unitl you start your other controller to test.

If it can talk to your aps´s it will work, with the docker (you could probably just see if the ap.s answears to requests on the offical ports to test this, with someting lilke" telnet IP 80" an see it it answears)

Pls let me know where you are from and what ap´s you use would be really cool to see if there is an global differnece to hardware on on theese things.
